-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(7aa2f7)",
			inactive_border = "rgb(a9b1d6)",
		},
	},
	group = {
		col = {
			border_active = "rgb(7aa2f7)",
			border_inactive = "rgb(a9b1d6)",
			border_locked_active = "rgb(f7768e)",
			border_locked_inactive = "rgb(a9b1d6)",
		},
		groupbar = {
			col = {
				active = "rgb(7aa2f7)",
				inactive = "rgb(a9b1d6)",
				locked_active = "rgb(f7768e)",
				locked_inactive = "rgb(a9b1d6)",
			},
		},
	},
})
