git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
customCommands:
  - key: '<c-space>'
    command: 'git diff --color-words {{.SelectedFile.Name}}'
    context: 'global'
    subprocess: true
