require("psto/impatient") -- needs to be first
require("psto/options")
require("psto/autocommands")
require("psto/plugins")
require("psto/keymaps")
require("psto/colorscheme")
require("psto/telescope/setup")
require("psto/telescope/mappings")
require("psto/lsp")
require("psto/completion")
require("psto/alpha")
require("psto/autopairs")
require("psto/gitsigns")
require("psto/lualine")
require("psto/rest")
require("psto/spectre")
require("psto/toggleterm")
require("psto/treesitter")
require("psto/trouble")
-- require("psto/twilight")
require("psto/whichkey")
-- require("psto/zenmode")
