#!/bin/sh
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# nvim
alias nvimrc='nvim ~/.config/nvim/'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
alias tr='trash-put'

# easier to read disk
alias free='free -m'            # show sizes in MB
alias df='df -h'                # human-readable sizes
alias du='du -sh'               # summarize folder disk usage
alias ncdu='ncdu --color dark'  # current directory by space usage

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

# git aliases
alias m="git checkout master"
alias s="git checkout stable"
alias gs="git status -sb"
alias ga="git add"
alias gc="git commit -m"
alias gd='git diff'
# "git lg" alias for pretty git log - set and forget
# git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"

# stdout to clipboard
alias copy='xclip -selection clipboard'
alias paste='xclip -selection clipboard -o'

# open
alias open="xdg-open"

# clear alias when in tmux
alias c='clear'

# yarn alias for XDG Base Directory
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

# exa alias
alias l='exa -l'

# ranger alias
alias r='ranger'

# lf alias
alias lf=lf-ueberzug

# Easily search running processes
alias psf='ps -Ao comm,pcpu,pmem,pid --sort=-pcpu | grep '

# mpv remember last played position
alias mpvsp='mpv --save-position-on-quit'

# cheat
cheat() { curl "http://cheat.sh/$1"; }

# get weather
alias wttr="curl wttr.in/Lubań"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
