#!/bin/sh
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Other XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}

# Disable files
export LESSHISTFILE=-

# Fixing Paths
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export COREPACK_HOME="$XDG_CACHE_HOME/node/corepack"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export IPFS_PATH="$XDG_CONFIG_HOME/ipfs/"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/config"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export RYE_HOME="$XDG_DATA_HOME/rye"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export TASKRC="$XDG_CONFIG_HOME/task/taskrc"
export TASKDATA="$XDG_DATA_HOME/task/"
export TERMINFO="$XDG_DATA_HOME"/terminfo # after installing wezterm terminfo file
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export W3M_DIR="$XDG_STATE_HOME/w3m"
export ZK_NOTEBOOK_DIR="$HOME/public/documents/notes/obsidian-notes/"

# FZF
export FZF_DEFAULT_COMMAND="rg --files --hidden --ignore-file ~/.config/git/gitignore"
export FZF_DEFAULT_OPTS="--highlight-line --info=inline-right --ansi --layout=reverse --border=none --color=bg+:#283457 --color=bg:#16161e --color=border:#27a1b9 --color=fg:#c0caf5 --color=gutter:#16161e --color=header:#ff9e64 --color=hl+:#2ac3de --color=hl:#2ac3de --color=info:#545c7e --color=marker:#ff007c --color=pointer:#ff007c --color=prompt:#2ac3de --color=query:#c0caf5:regular --color=scrollbar:#27a1b9 --color=separator:#ff9e64 --color=spinner:#ff007c"
export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always {}' --no-height --preview-window=65% --bind 'ctrl-o:execute(xdg-open {})' --bind 'ctrl-e:execute(nvim {})' --bind 'ctrl-a:select-all' --bind 'ctrl-c:deselect-all'"
export FZF_CTRL_R_OPTS="$(
	cat <<'FZF_FTW'
--bind "ctrl-d:execute-silent(zsh -ic 'builtin fc -p $HISTFILE $HISTSIZE $SAVEHIST; for i in {+1}; do ignore+=( \"${(b)history[$i]}\" );done;
	HISTORY_IGNORE=\"(${(j:|:)ignore})\";builtin fc -W $HISTFILE')+reload:builtin fc -p $HISTFILE $HISTSIZE $SAVEHIST; builtin fc -rl 1 |
	awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, \"\", cmd); if (!seen[cmd]++) print $0 }'"
--bind 'enter:accept-or-print-query'
--header 'enter select · ^d remove'
--prompt ' Global History > '
FZF_FTW
)"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# fnm for node
eval "$(fnm env --use-on-cd)"
# npm for node.js
export PATH="$XDG_DATA_HOME/npm/bin:$PATH"

# Add rbnev to PATH
export PATH="$RBENV_ROOT/bin:$PATH"
# eval "$(rbenv init - zsh)"
export PATH="$RBENV_ROOT/plugins/ruby-build/bin:$PATH"
# Install Ruby Gems to ~/.gems
export GEM_HOME="$XDG_DATA_HOME"/gems
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gems
export PATH="$XDG_DATA_HOME/gems/bin:$PATH"

# cargo PATH
export PATH=$XDG_DATA_HOME/cargo/bin:$PATH

# go PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# eval "`pip completion --zsh`"

# deno deploy
export PATH="$XDG_DATA_HOME/deno/bin:$PATH"

# Bun
export BUN_INSTALL="$XDG_DATA_HOME/bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# Bun completions
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"
