#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Other XDG paths
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}

# Disable files
export LESSHISTFILE=-

# Fixing Paths
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export COREPACK_HOME="$XDG_CACHE_HOME/node/corepack"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export IPFS_PATH="$XDG_CONFIG_HOME/ipfs/"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc 
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export TERMINFO="$XDG_DATA_HOME"/terminfo # after installing wezterm terminfo file
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export W3M_DIR="$XDG_STATE_HOME/w3m" 

# fnm for node
eval "$(fnm env --use-on-cd)"
# npm for node.js
export PATH="$XDG_DATA_HOME/npm/bin:$PATH"

# Add rbnev to PATH
export PATH="$RBENV_ROOT/bin:$PATH"
eval "$(rbenv init - zsh)"
export PATH="$RBENV_ROOT/plugins/ruby-build/bin:$PATH"
# Install Ruby Gems to ~/.gems
# export GEM_HOME="$HOME/.gems"
export GEM_HOME="$XDG_DATA_HOME"/gems
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gems
export PATH="$XDG_DATA_HOME/gems/bin:$PATH"

# cargo PATH
export PATH=$XDG_DATA_HOME/cargo/bin:$PATH

# go PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go

# eval "`pip completion --zsh`"

# deno deploy
export PATH="$XDG_DATA_HOME/deno/bin:$PATH"

# Bun
export BUN_INSTALL="$XDG_DATA_HOME/bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# bun completions
[ -s "$BUN_INSTALL/_bun" ] && source "$BUN_INSTALL/_bun"
