#!/bin/sh
alias sudo='doas'
alias sudoedit='doas $EDITOR'
alias doasedit='doas $EDITOR'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# nvim
alias nvimrc='nvim ~/.config/nvim/'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# get fastest mirrors
alias mirror="doas reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="doas reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="doas reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="doas reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'

# confirm before overwriting something
alias cp="cp -riv"
alias mv='mv -iv'
alias rm='rm -riv'
alias mkdir='mkdir -pv'

# trash
alias rmt="trashy put"
alias rml="trashy list"
alias rmr="trashy restore"
alias rme="trashy empty --all"

# easier to read disk
alias free='free -m'            # show sizes in MB
alias df='df -h'                # human-readable sizes
alias du='du -sh'               # summarize folder disk usage
alias ncdu='ncdu --color dark'  # current directory by space usage

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="doas pacman-key --init && doas pacman-key --populate archlinux && doas pacman-key --refresh-keys"

# fuzzy-search and install available pacman packages
alias pacmani="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro doas pacman -S"
# fuzzy-search and install available aur packages
alias parui="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S"
# list and remove installed packages
alias pacmanrm="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro doas pacman -Rns"
alias parurm="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rns"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

# git aliases
alias g='lazygit'
alias lg='lazygit'
alias gs="git status -sb"
alias ga="git add"
alias gap="git add --patch"
alias gb="git branch"
alias gba="git branch --all"
alias gbd="git branch -D"
alias gc="git commit"
alias gco="git checkout"
alias gcb="git branch | fzf | xargs git checkout"
alias gcl="git clone"
alias gcp="git cherry-pick"
alias gd="git diff -w"
alias gdw="git diff-words"
alias gds="git diff --staged"
alias gp="git push"
alias gpl="git pull"
alias gpr="git pull --rebase"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias grf="git reflog --date=iso"
alias grfp="git reflog --date=iso --pretty"
# "git lg" alias for pretty git log - set and forget
# git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gl="git lg"
alias gca="git commit --amend"
alias gcan="git commit --amend --no-edit"
alias gw="git worktree"
alias gwa="git worktree add"
alias gwl="git worktree list"
alias gwr="git worktree remove"
alias gh-create-private='gh repo create --private --source=. --remote=origin && git push -u --all && gh browse'
alias gh-create-public='gh repo create --public --source=. --remote=origin && git push -u --all && gh browse'

# open
alias open="xdg-open"

# fzf open editor
alias e='fzf -m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all --print0 --preview "bat --theme Dracula --color=always {}" | xargs -0 -o $EDITOR'

# clear alias when in tmux
alias c='clear'

alias ls='ls -F --color=auto'
# eza alias
alias l='eza -l --icons'
alias la='eza -a --icons'
alias ll='eza -al --group-directories-first'  # list directories first
alias lt='eza -al --sort=modified'            # list by modified date
alias lz='eza -alFr --color=always --sort=size | grep -v /' # list files by size

# xplr alias
alias x="xplr"

# navi alias
alias n="navi"

# Easily search running processes
alias psf='ps -Ao comm,pcpu,pmem,pid --sort=-pcpu | grep '

# mpv
alias mpvsp='mpv --save-position-on-quit' # mpv remember last played position

# cheat
cheat() { curl "http://cheat.sh/$1"; }

# get weather, set $HOMETOWN in /etc/environment                        21:07:01
alias wttr="curl wttr.in/$HOMETOWN"

# dragon-drop
alias drag="dragon-drop"

# transmission-remote
alias tsm="transmission-remote"

# translate
alias trpl="trans :pl"
alias tren="trans pl:en"

# yt-dlp
alias yt="yt-dlp -S res,ext:mp4:m4a --recode mp4"
alias yt-subs='yt-dlp --write-sub --write-auto-sub --sub-lang "en.*" --skip-download' #download subtitles only
