[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "fd --hidden -t f . $HOME/.dotfiles"


[preview]
command = "bat -n --color=always '{}'"
