cursor #364a82
cursor_text_color #414868

foreground            #364a82
background            #ffffff
selection_foreground  #ffffff
selection_background  #bb9af7
url_color             #7aa2f7

color0   #1a1b26
color1   #ea5c83
color2   #3fb951
color3   #fff63d
color4   #77a2ff
color5   #d5e2ff
color6   #7aa2f7
color7   #424345
color8   #ccced1
color9   #ff7da1
color10  #71ff86
color11  #fff64a
color12  #719eff
color13  #d5e2ff
color14  #bed3ff
color15  #f9fbff
